server.port=8081

spring.datasource.url=jdbc:mariadb://147.50.254.12:3306/ppavis_oneclickpro
spring.datasource.username=ppavis_dbadmin
spring.datasource.password=g0pN0jkp0[
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true