server.port=${PORT:8081}

spring.datasource.url=jdbc:mariadb://147.50.254.12:3306/ppavis_oneclickpro
spring.datasource.username=ppavis_dbadmin
spring.datasource.password=g0pN0jkp0[
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

line.channel-access-token=5Na8zgJ7Q0XwD9ROWEFpUrMyyIYntNG0rLc6Zf06aVRqKJgGX33pP6M2bWQ7L15YG2fGUX7Cp1Ab2xPt7VOtNJsczleRvVww4SkleiF99/x1D4W5tZFJdarGMb7k+KPayiDXTSs1sxC7kcygYri4sAdB04t89/1O/w1cDnyilFU=
line.channel-secret=eb8d9a204914c8120d2c7ab268bca24e
line.group-id=C9ca646fcf542347b9e10a5ef16dbf014